<a href="https://colab.research.google.com/github/ahyoungKwon/aipython/blob/main/240503.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Lab 1-1
import numpy as np
arr = np.arange(1, 10, 2)
print(arr)

[1 3 5 7 9]


In [ ]:
# Lab 1-2
one = np.ones((3, 4))
print(one)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# Lab 1-3
arr = np.linspace(0, 1, 10)
print(arr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [10]:
# Lab 2
A = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20], [21, 22, 23, 24, 25]])

#모양 출력
print(A.shape)

# 19 값 출력
print(A[3, 3])

# [[1,2], [6, 7]] 값 출력
print(A[:2, :2])

#[[19, 20], [24, 25]] 값 출력
print(A[3: , 3: ])

#1행, 2행 출력 - 열 인덱스 생략 가능
print(A[:2, ])

#4열, 5열 출력 - 행은 생략 불가(: 쳐야 함)
print(A[ : ,3:])

(5, 5)
19
[[1 2]
 [6 7]]
[[19 20]
 [24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]


In [ ]:
B = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12],

               [13, 14, 15, 16],
               [17, 18, 19, 20],
              [21, 22, 23, 24]],

              [[25, 26, 27, 28],
              [29, 30, 31, 32],
              [33, 34, 35, 36]]])

# 1차원으로 배열 만들고 rehape(3, 3, 4)로 3차원으로 배열 바꿈

In [21]:
# Lab 3

# 행렬 생성
B = np.arange(1, 37)
B = B.reshape(3, 3, 4)
print(B)

# 모양, 크기 출력
print(B.shape)
print(B.size)

#모양 (3, 4, 3)으로 변경
newB = B.reshape(3, 4, 3)
print(newB)

# 1차원 배열로 구성
newB2 = B.flatten()
print(newB2)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]
(3, 3, 4)
36
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
